# Generated by Django 3.2.9 on 2021-11-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211123_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_in_school_status',
            field=models.CharField(choices=[('student', 'ученик'), ('teacher', 'учитель'), ('parent', 'родитель'), ('moderator', 'модератор'), ('admin', 'админ')], default='student', max_length=32),
        ),
    ]
