# Generated by Django 3.2.9 on 2021-12-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_user_in_school_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='district',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
