version: '3'
services:
  django:
    build: 
      context: ./
      dockerfile: ./compose/local/Dockerfile
    volumes:
      - .:/app:z
    ports: 
      - "8000:8000"
    env_file:
      - .envs/.local
    depends_on:
      - db
      - redis
    command:
      - /start

  db:
    image: postgres
    volumes: 
      - db-data:/var/lib/postgres/data
    env_file:
      - .envs/.local

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - 'redis-data:/data'
  
volumes:
  db-data:
  redis-data:

networks:
  new_app:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24