# Generated by Django 3.2.9 on 2021-11-25 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=512)),
                ('date', models.DateTimeField(auto_now=True)),
                ('is_forwarded', models.BooleanField(default=False)),
                ('reply_to_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_message', to='chat.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='chat/photos')),
                ('title', models.CharField(max_length=128)),
                ('about', models.CharField(max_length=1024)),
                ('who_can_edit_chat', models.CharField(choices=[('everybody', 'Все'), ('admins_and_moders', 'Админы и модераторы'), ('admins', 'Админы')], default='everybody', max_length=32)),
                ('is_group', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('admins', models.ManyToManyField(related_name='admin_in_chats', to=settings.AUTH_USER_MODEL)),
                ('moderators', models.ManyToManyField(related_name='moder_in_chats', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
