# Generated by Django 3.2.9 on 2021-11-25 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_auto_20211125_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='admins',
            field=models.ManyToManyField(blank=True, default=[], related_name='admin_in_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='moderators',
            field=models.ManyToManyField(blank=True, default=[], related_name='moder_in_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(blank=True, default=[], related_name='chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
