# Generated by Django 3.2.9 on 2021-11-25 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20211125_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reply_to_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_message', to='chat.message'),
        ),
    ]
