# Generated by Django 3.2.9 on 2021-11-29 06:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0009_auto_20211127_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='banned_list',
            field=models.ManyToManyField(blank=True, default=[], related_name='banned_in_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
