# Generated by Django 3.2.9 on 2021-11-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20211129_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgfileupload',
            name='file',
            field=models.FileField(upload_to='chat/message/imgs'),
        ),
    ]
