# Generated by Django 3.2.9 on 2021-11-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_imgfileupload_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='docs',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='imgs',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='videos',
        ),
        migrations.AddField(
            model_name='message',
            name='docs',
            field=models.ManyToManyField(blank=True, default=[], related_name='messages', to='chat.DocFileUpload'),
        ),
        migrations.AddField(
            model_name='message',
            name='imgs',
            field=models.ManyToManyField(blank=True, default=[], related_name='messages', to='chat.ImgFileUpload'),
        ),
        migrations.DeleteModel(
            name='VideoFileUpload',
        ),
    ]
