# Generated by Django 3.2.9 on 2021-11-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20211130_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='docfileupload',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
