# Generated by Django 3.2.9 on 2021-12-03 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='add_smt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_to_add', models.CharField(choices=[('offers', 'предложения'), ('requsts', 'запросы'), ('quastions', 'вопросы')], default='offers', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titele', models.CharField(max_length=64, verbose_name='Имя предложения')),
                ('about', models.TextField(verbose_name='Описание предложения....')),
                ('back', models.TextField(verbose_name='Что вы ъотите в замен?')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='quastions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titele', models.CharField(max_length=64, verbose_name='Имя вопроса')),
                ('about', models.TextField(verbose_name='Описание вопроса....')),
            ],
        ),
        migrations.CreateModel(
            name='requsts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titele', models.CharField(max_length=64, verbose_name='Имя запроса')),
                ('about', models.TextField(verbose_name='Описание запроса....')),
            ],
        ),
        migrations.CreateModel(
            name='offers_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('define_type_of_request', models.CharField(choices=[('offers', 'предложения'), ('requsts', 'запросы'), ('quastions', 'вопросы')], default='offers', max_length=32)),
                ('offers_f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL, verbose_name='предложения')),
                ('quastions_F', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quastions', to=settings.AUTH_USER_MODEL, verbose_name='вопросы')),
                ('requsts_f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requsts', to=settings.AUTH_USER_MODEL, verbose_name='запросы')),
            ],
        ),
    ]
