# Generated by Django 3.2.9 on 2021-12-03 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requsts',
            name='back',
            field=models.TextField(default=0, verbose_name='Что вы готовы дать за вопрос?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requsts',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='offers',
            name='back',
            field=models.TextField(verbose_name='Что вы хотите в замен?'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='offers_main',
            name='offers_f',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.offers', verbose_name='предложения'),
        ),
        migrations.AlterField(
            model_name='offers_main',
            name='quastions_F',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.quastions', verbose_name='вопросы'),
        ),
        migrations.AlterField(
            model_name='offers_main',
            name='requsts_f',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.requsts', verbose_name='запросы'),
        ),
    ]
