# Generated by Django 3.2.9 on 2021-12-03 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0002_auto_20211204_0021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add_smt',
        ),
        migrations.RemoveField(
            model_name='offers_main',
            name='offers_f',
        ),
        migrations.RemoveField(
            model_name='offers_main',
            name='quastions_F',
        ),
        migrations.RemoveField(
            model_name='offers_main',
            name='requsts_f',
        ),
        migrations.AddField(
            model_name='offers_main',
            name='about',
            field=models.TextField(default=0, verbose_name='Описание предложения....'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offers_main',
            name='back',
            field=models.TextField(default=0, verbose_name='Что вы хотите в замен?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offers_main',
            name='by_who',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offers_main',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='offers_main',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='offers_main',
            name='titele',
            field=models.CharField(default=0, max_length=64, verbose_name='Имя предложения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offers_main',
            name='views_amoun',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='offers',
        ),
        migrations.DeleteModel(
            name='quastions',
        ),
        migrations.DeleteModel(
            name='requsts',
        ),
    ]
