# Generated by Django 3.2.9 on 2021-12-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_auto_20211204_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers_main',
            name='views_amoun',
            field=models.BigIntegerField(),
        ),
    ]
