# Generated by Django 3.2.9 on 2021-12-04 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0005_alter_offers_main_views_amoun'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffersMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('define_type_of_request', models.CharField(choices=[('offers', 'предложения'), ('requsts', 'запросы'), ('quastions', 'вопросы')], default='offers', max_length=32)),
                ('titele', models.CharField(max_length=64, verbose_name='Имя предложения')),
                ('about', models.TextField(verbose_name='Описание предложения....')),
                ('back', models.TextField(verbose_name='Что вы хотите в замен?')),
                ('date', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('views_amoun', models.BigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='offers_main',
        ),
    ]
