# Generated by Django 3.2.9 on 2021-12-04 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_auto_20211204_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offersmain',
            old_name='titele',
            new_name='title',
        ),
    ]
