# Generated by Django 3.2.9 on 2021-12-05 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_rename_titele_offersmain_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offersmain',
            options={'ordering': ['date']},
        ),
    ]
