# Generated by Django 3.2.10 on 2021-12-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_alter_offersmain_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offersmain',
            options={'ordering': ('date',)},
        ),
        migrations.AlterField(
            model_name='offersmain',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
