# Generated by Django 3.2.10 on 2021-12-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_auto_20211209_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='offersmain',
            name='define_type_of_subjecte',
            field=models.CharField(choices=[('math', 'математика'), ('sport', 'спорт'), ('rushen', 'русский'), ('biolohy', 'биология'), ('physiks', 'физика'), ('english', 'англиский'), ('letracher', 'литература'), ('it', 'информатика'), ('programming', 'программирование'), ('music', 'музыка'), ('drow', 'рисование'), ('geometry', 'геометрия'), ('geo', 'география'), ('geo_drow', 'черчение'), ('comp_game', 'компьютерные игры'), ('other', 'другое')], default='other', max_length=64),
        ),
    ]
