# Generated by Django 3.2.10 on 2021-12-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_offersmain_define_type_of_subjecte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offersmain',
            name='define_type_of_subjecte',
            field=models.CharField(choices=[('math', 'математика'), ('sport', 'спорт'), ('rushen', 'русский'), ('biology', 'биология'), ('physics', 'физика'), ('english', 'англиский'), ('literature', 'литература'), ('it', 'информатика'), ('programming', 'программирование'), ('music', 'музыка'), ('draw', 'рисование'), ('geometry', 'геометрия'), ('geography', 'география'), ('drawing', 'ИЗО'), ('comp_games', 'компьютерные игры'), ('other', 'другое')], default='other', max_length=64),
        ),
    ]
