# Generated by Django 3.2.10 on 2021-12-11 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0011_alter_offersmain_define_type_of_subjecte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offersmain',
            old_name='define_type_of_subjecte',
            new_name='define_type_of_subject',
        ),
    ]
