# Generated by Django 3.2.10 on 2021-12-11 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0014_auto_20211211_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offersmain',
            old_name='define_type_of_subject',
            new_name='subject',
        ),
    ]
