# Generated by Django 3.2.10 on 2021-12-11 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0015_rename_define_type_of_subject_offersmain_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='title',
        ),
    ]
