# Generated by Django 3.2.10 on 2021-12-11 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0016_rename_name_subject_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='title',
            new_name='name',
        ),
    ]
