# Generated by Django 3.2.10 on 2021-12-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0017_rename_title_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='offersmain',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
