# Generated by Django 3.2.10 on 2021-12-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0018_offersmain_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offersmain',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Архивировано'),
        ),
        migrations.AlterField(
            model_name='offersmain',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Архивировано'),
        ),
        migrations.AlterField(
            model_name='offersmain',
            name='views_amoun',
            field=models.BigIntegerField(default=0, verbose_name='Просмотры (пока не работает)'),
        ),
    ]
