# Generated by Django 3.2.10 on 2021-12-13 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0019_auto_20211213_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offersmain',
            name='is_published',
        ),
    ]
